/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CheckboxGroup: typeof import('./components/checkboxGroup.vue')['default']
    Inputs: typeof import('./components/inputs.vue')['default']
    Results: typeof import('./components/results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/settings.vue')['default']
  }
}
